version: '2'
services:
  php:
    build:
      context: ./docker
      dockerfile: /Dockerfile_php
    volumes:
      - ./app:/code/:ro
    environment:
        VSTACK_DBHOST: '10.222.1.2'
        VSTACK_DBUSER: 'vstack_user'
        VSTACK_PASSWORD: 'DV2JLlizYu7pbktu01Qi'
        VSTACK_DBNAME: 'vstack_db'
  web:
    image: nginx
    restart: always
    volumes:
      - ./app:/code/:ro
      - ./docker/config/nginx_default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    environment:
      NGINX_PORT: "80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    links:
      - php
