version: '2'
services:
  web:
    image: nginx
    volumes:
      - ~/code/vstack/app:/code
      - ~/code/vstack/docker/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      NGINX_PORT: "80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    links:
      - php
  php:
    image: php:5-fpm
    volumes:
       - ~/code/vstack/app:/code
