version: '2'
services:
  php:
    build:
      context: ./docker
      dockerfile: /Dockerfile_php
    volumes:
       - ~/code/vstack/app:/code
  web:
    image: nginx
    restart: always
    volumes:
      - ~/code/vstack/app:/code
      - ~/code/vstack/docker/config/nginx_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      NGINX_PORT: "80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    links:
      - php
