---
- hosts: vstack
  gather_facts: False
  become: True  
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - setup: # Run setup module to gather facts here.
  roles:
    - { role: swapfile,
        swapfile_size: 1024MB }
    - { role: ansible-role-mysql,
        mysql_databases: [{
            name: 'vstack_db',
            collation: 'utf8_general_ci',
            encoding: 'utf8'
        }],
        mysql_users: [
        {
          name: 'vstack_user',
          password: 'DV2JLlizYu7pbktu01Qi',
          priv: 'vstack_db.*:ALL',
          host: "%" },
        {
          name: 'vstack_user',
          password: 'DV2JLlizYu7pbktu01Qi',
          priv: 'vstack_db.*:ALL',
          host: "localhost" }],
         tags: ['mysql']
      }
    - { role: ansible-role-php,
        php_enable_php_fpm: true,
        php_webserver_daemon: "nginx",
        php_packages: [
            'php-mysql',
            'php7.0-common',
            'php7.0-cli',
            'php7.0-dev',
            'php7.0-fpm',
            'libpcre3-dev',
            'php7.0-gd',
            'php7.0-curl',
            'php7.0-imap',
            'php7.0-json',
            'php7.0-opcache',
            'php7.0-xml',
            'php7.0-mbstring',
            'php-sqlite3',
            'php-apcu',
            'php7.0-mcrypt'
        ]
      }
    - { role: ansible-role-nginx,
        nginx_remove_default_vhost: true,
        nginx_vhosts: [{
          listen: "80 default_server",
          server_name: "_",
          root: "/usr/share/nginx/html",
          index: "index.php index.html index.htm",
          extra_parameters: "{{nginx_extra_params}}"
        }]
      }
    - app
