---
- hosts: vstack
  become: True
  roles:
    - { role: common }
    - { role: swapfile,
        swapfile_size: 1024MB }
    - { role: ansible-role-mysql,
        mysql_databases: [{
            name: '{{vstack_dbname}}',
            collation: 'utf8_general_ci',
            encoding: 'utf8'
        }],
        mysql_users: [{
          name: '{{vstack_dbuser}}',
          password: '{{vstack_dbpassword}}',
          priv: '{{vstack_dbname}}.*:ALL',
          host: "%" }] 
      }
    - { role: website,
        tags: "website" }
