---
- hosts: vstack
  become: True
  roles:
    - { role: common }
    - { role: swapfile,
        swapfile_size: 1024MB }
    - { role: ansible-role-mysql,
        mysql_databases: [{
            name: 'vstack_db',
            collation: 'utf8_general_ci',
            encoding: 'utf8'
        }],
        mysql_users: [{
          name: 'vstack_user',
          password: 'DV2JLlizYu7pbktu01Qi',
          priv: 'vstack_db.*:ALL',
          host: "%" }] 
      }
    - { role: website,
        tags: "website" }
