CREATE TABLE IF NOT EXISTS items (
	Id int PRIMARY KEY NOT NULL,
	Content VARCHAR(1024) CHARSET utf8
);

INSERT INTO items (Id, Content) VALUES (1, "FOO")
ON DUPLICATE KEY UPDATE Content="FOO_NEW";

INSERT INTO items (Id, Content) VALUES (2, "BAR")
ON DUPLICATE KEY UPDATE Content="BAR_NEW";

INSERT INTO items (Id, Content) VALUES (3, "BAZ")
ON DUPLICATE KEY UPDATE Content="BAZ_NEW";

