- name: nginx | install nginx
  apt: pkg=nginx
  become: True

- name: create website directory
  file: 
    path: "{{website_path}}"
    state: directory 
    owner: www-data 
    group: www-data 
    mode: 777

- name: git pull latest version of code
  git: 
    repo: https://github.com/mekuls/vstack.git 
    dest: "{{website_path}}" 

- name: Ensure everything is chowned to www-data
  shell: "chown -R www-data:www-data {{website_path}}"

- name: Ensure directories are 0755
  command: find {{ website_path }} -type d -exec chmod -c 0755 {} \;
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""

- name: Ensure files are 0644
  command: find {{ website_path }} -type f -exec chmod -c 0644 {} \;
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""

- name: nginx | remove default configurations
  file: path={{item.src}} state=absent
  with_items:
    - { src: '/etc/nginx/sites-enabled/default' }
    - { src: '/etc/nginx/sites-available/default' }
  become: True
  notify:
    - nginx | reload nginx

- name: setting up templates
  template: src=templates/{{ item }} dest={{ item }}
  with_items:
    - /etc/nginx/conf.d/php.conf
    - /etc/nginx/sites-available/vstack.conf

- name: nginx | symlinking sites-available
  file:
    src: "/etc/nginx/sites-available/{{item}}"
    dest: "/etc/nginx/sites-enabled/{{item}}"
    state: link
  with_items:
    - vstack.conf 
  become: True
  notify:
    - nginx | reload nginx

- name: installing php5-fpm
  apt: pkg=php5-fpm

- name: securing php5-fpm
  replace: dest=/etc/php5/fpm/php.ini regexp=^;cgi.fix_pathinfo=1 replace=cgi.fix_pathinfo=0
  notify:
    - "php5-fpm | reload"

- name: copying php5-fpm default pool template
  template: 
    src: templates/etc/php5/fpm/pool.d/www.conf
    dest: /etc/php5/fpm/pool.d/www.conf
  notify:
    - "php5-fpm | reload"

- name: installing php5 modules
  apt: pkg={{ item }}
  with_items:
    - php5-mysql
    - php5-curl
  notify:
    - php5-fpm | reload
    - nginx | reload nginx

- name: setting environment variables
  lineinfile:
    dest: "/etc/php5/fpm/pool.d/www.conf"
    regexp: "^env[VSTACK_DBHOST]"
    line: "env[VSTACK_DBHOST] = {{vstack_dbhost}}"
    state: "present"
  notify:
    - "php5-fpm | restart"

